// Generated by Futhark 0.25.29.
// Compiled with GHC 9.8.4.
#pragma once


// Headers
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <float.h>

#include <cuda.h>
#include <cuda_runtime.h>
#include <nvrtc.h>

#ifdef __cplusplus
extern "C" {
#endif

// Initialisation
struct futhark_context_config;
struct futhark_context_config *futhark_context_config_new(void);
void futhark_context_config_free(struct futhark_context_config *cfg);
int futhark_context_config_set_tuning_param(struct futhark_context_config *cfg, const char *param_name, size_t new_value);
struct futhark_context;
struct futhark_context *futhark_context_new(struct futhark_context_config *cfg);
void futhark_context_free(struct futhark_context *cfg);
void futhark_context_config_set_default_thread_block_size(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_grid_size(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_group_size(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_num_groups(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_tile_size(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_reg_tile_size(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_registers(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_cache(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_threshold(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_unified_memory(struct futhark_context_config *cfg, int flag);
void futhark_context_config_add_nvrtc_option(struct futhark_context_config *cfg, const char *opt);
void futhark_context_config_set_device(struct futhark_context_config *cfg, const char *s);
const char *futhark_context_config_get_program(struct futhark_context_config *cfg);
void futhark_context_config_set_program(struct futhark_context_config *cfg, const char *s);
void futhark_context_config_dump_ptx_to(struct futhark_context_config *cfg, const char *s);
void futhark_context_config_load_ptx_from(struct futhark_context_config *cfg, const char *s);
void futhark_context_config_set_debugging(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_profiling(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_logging(struct futhark_context_config *cfg, int flag);
int futhark_get_tuning_param_count(void);
const char *futhark_get_tuning_param_name(int);
const char *futhark_get_tuning_param_class(int);

// Arrays
struct futhark_f16_2d;
struct futhark_f16_2d *futhark_new_f16_2d(struct futhark_context *ctx, const uint16_t *data, int64_t dim0, int64_t dim1);
struct futhark_f16_2d *futhark_new_raw_f16_2d(struct futhark_context *ctx, CUdeviceptr data, int64_t dim0, int64_t dim1);
int futhark_free_f16_2d(struct futhark_context *ctx, struct futhark_f16_2d *arr);
int futhark_values_f16_2d(struct futhark_context *ctx, struct futhark_f16_2d *arr, uint16_t *data);
int futhark_index_f16_2d(struct futhark_context *ctx, uint16_t *out, struct futhark_f16_2d *arr, int64_t i0, int64_t i1);
CUdeviceptr futhark_values_raw_f16_2d(struct futhark_context *ctx, struct futhark_f16_2d *arr);
const int64_t *futhark_shape_f16_2d(struct futhark_context *ctx, struct futhark_f16_2d *arr);
struct futhark_f16_3d;
struct futhark_f16_3d *futhark_new_f16_3d(struct futhark_context *ctx, const uint16_t *data, int64_t dim0, int64_t dim1, int64_t dim2);
struct futhark_f16_3d *futhark_new_raw_f16_3d(struct futhark_context *ctx, CUdeviceptr data, int64_t dim0, int64_t dim1, int64_t dim2);
int futhark_free_f16_3d(struct futhark_context *ctx, struct futhark_f16_3d *arr);
int futhark_values_f16_3d(struct futhark_context *ctx, struct futhark_f16_3d *arr, uint16_t *data);
int futhark_index_f16_3d(struct futhark_context *ctx, uint16_t *out, struct futhark_f16_3d *arr, int64_t i0, int64_t i1, int64_t i2);
CUdeviceptr futhark_values_raw_f16_3d(struct futhark_context *ctx, struct futhark_f16_3d *arr);
const int64_t *futhark_shape_f16_3d(struct futhark_context *ctx, struct futhark_f16_3d *arr);
struct futhark_f32_1d;
struct futhark_f32_1d *futhark_new_f32_1d(struct futhark_context *ctx, const float *data, int64_t dim0);
struct futhark_f32_1d *futhark_new_raw_f32_1d(struct futhark_context *ctx, CUdeviceptr data, int64_t dim0);
int futhark_free_f32_1d(struct futhark_context *ctx, struct futhark_f32_1d *arr);
int futhark_values_f32_1d(struct futhark_context *ctx, struct futhark_f32_1d *arr, float *data);
int futhark_index_f32_1d(struct futhark_context *ctx, float *out, struct futhark_f32_1d *arr, int64_t i0);
CUdeviceptr futhark_values_raw_f32_1d(struct futhark_context *ctx, struct futhark_f32_1d *arr);
const int64_t *futhark_shape_f32_1d(struct futhark_context *ctx, struct futhark_f32_1d *arr);
struct futhark_f32_2d;
struct futhark_f32_2d *futhark_new_f32_2d(struct futhark_context *ctx, const float *data, int64_t dim0, int64_t dim1);
struct futhark_f32_2d *futhark_new_raw_f32_2d(struct futhark_context *ctx, CUdeviceptr data, int64_t dim0, int64_t dim1);
int futhark_free_f32_2d(struct futhark_context *ctx, struct futhark_f32_2d *arr);
int futhark_values_f32_2d(struct futhark_context *ctx, struct futhark_f32_2d *arr, float *data);
int futhark_index_f32_2d(struct futhark_context *ctx, float *out, struct futhark_f32_2d *arr, int64_t i0, int64_t i1);
CUdeviceptr futhark_values_raw_f32_2d(struct futhark_context *ctx, struct futhark_f32_2d *arr);
const int64_t *futhark_shape_f32_2d(struct futhark_context *ctx, struct futhark_f32_2d *arr);
struct futhark_f32_3d;
struct futhark_f32_3d *futhark_new_f32_3d(struct futhark_context *ctx, const float *data, int64_t dim0, int64_t dim1, int64_t dim2);
struct futhark_f32_3d *futhark_new_raw_f32_3d(struct futhark_context *ctx, CUdeviceptr data, int64_t dim0, int64_t dim1, int64_t dim2);
int futhark_free_f32_3d(struct futhark_context *ctx, struct futhark_f32_3d *arr);
int futhark_values_f32_3d(struct futhark_context *ctx, struct futhark_f32_3d *arr, float *data);
int futhark_index_f32_3d(struct futhark_context *ctx, float *out, struct futhark_f32_3d *arr, int64_t i0, int64_t i1, int64_t i2);
CUdeviceptr futhark_values_raw_f32_3d(struct futhark_context *ctx, struct futhark_f32_3d *arr);
const int64_t *futhark_shape_f32_3d(struct futhark_context *ctx, struct futhark_f32_3d *arr);
struct futhark_i64_1d;
struct futhark_i64_1d *futhark_new_i64_1d(struct futhark_context *ctx, const int64_t *data, int64_t dim0);
struct futhark_i64_1d *futhark_new_raw_i64_1d(struct futhark_context *ctx, CUdeviceptr data, int64_t dim0);
int futhark_free_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
int futhark_values_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr, int64_t *data);
int futhark_index_i64_1d(struct futhark_context *ctx, int64_t *out, struct futhark_i64_1d *arr, int64_t i0);
CUdeviceptr futhark_values_raw_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
const int64_t *futhark_shape_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
struct futhark_u64_1d;
struct futhark_u64_1d *futhark_new_u64_1d(struct futhark_context *ctx, const uint64_t *data, int64_t dim0);
struct futhark_u64_1d *futhark_new_raw_u64_1d(struct futhark_context *ctx, CUdeviceptr data, int64_t dim0);
int futhark_free_u64_1d(struct futhark_context *ctx, struct futhark_u64_1d *arr);
int futhark_values_u64_1d(struct futhark_context *ctx, struct futhark_u64_1d *arr, uint64_t *data);
int futhark_index_u64_1d(struct futhark_context *ctx, uint64_t *out, struct futhark_u64_1d *arr, int64_t i0);
CUdeviceptr futhark_values_raw_u64_1d(struct futhark_context *ctx, struct futhark_u64_1d *arr);
const int64_t *futhark_shape_u64_1d(struct futhark_context *ctx, struct futhark_u64_1d *arr);

// Opaque values



// Entry points
int futhark_entry_clip_matrix_global_norm_f32(struct futhark_context *ctx, struct futhark_f32_2d **out0, const struct futhark_f32_2d *in0, const float in1);
int futhark_entry_embedding_backward_padded(struct futhark_context *ctx, struct futhark_f32_2d **out0, const struct futhark_i64_1d *in0, const struct futhark_i64_1d *in1, const struct futhark_f16_3d *in2, const struct futhark_f32_2d *in3);
int futhark_entry_embedding_forward_padded(struct futhark_context *ctx, struct futhark_f16_3d **out0, const struct futhark_i64_1d *in0, const struct futhark_i64_1d *in1, const struct futhark_i64_1d *in2, const struct futhark_f16_2d *in3);
int futhark_entry_embedding_spectral_normalize(struct futhark_context *ctx, struct futhark_f32_2d **out0, struct futhark_f32_1d **out1, struct futhark_f32_1d **out2, float *out3, float *out4, const struct futhark_f32_2d *in0, const struct futhark_f32_1d *in1, const struct futhark_f32_1d *in2, const int64_t in3, const float in4);
int futhark_entry_embedding_sum_squares(struct futhark_context *ctx, float *out0, const struct futhark_f16_2d *in0);
int futhark_entry_embedding_update_sfd_master(struct futhark_context *ctx, struct futhark_f32_2d **out0, struct futhark_f32_2d **out1, struct futhark_f32_2d **out2, const struct futhark_f32_2d *in0, const struct futhark_f32_2d *in1, const struct futhark_f32_2d *in2, const struct futhark_f32_2d *in3, const float in4, const float in5, const float in6, const int64_t in7, const float in8, const float in9, const float in10);
int futhark_entry_graph_batch_encode(struct futhark_context *ctx, struct futhark_u64_1d **out0, struct futhark_f32_1d **out1, struct futhark_f32_1d **out2, struct futhark_f32_1d **out3, struct futhark_f32_1d **out4, struct futhark_i64_1d **out5, struct futhark_i64_1d **out6, const struct futhark_u64_1d *in0, const uint64_t in1);
int futhark_entry_master_weights_to_f16_2d(struct futhark_context *ctx, struct futhark_f16_2d **out0, const struct futhark_f32_2d *in0);
int futhark_entry_master_weights_to_f16_3d(struct futhark_context *ctx, struct futhark_f16_3d **out0, const struct futhark_f32_3d *in0);
int futhark_entry_matmul(struct futhark_context *ctx, struct futhark_f32_2d **out0, const struct futhark_f32_2d *in0, const struct futhark_f32_2d *in1);
int futhark_entry_rsf_forward(struct futhark_context *ctx, struct futhark_f16_2d **out0, const struct futhark_f16_2d *in0, const struct futhark_f16_2d *in1, const struct futhark_f16_2d *in2, const uint16_t in3, const uint16_t in4);
int futhark_entry_rsf_stack_backward_gradients_fused(struct futhark_context *ctx, struct futhark_f32_3d **out0, struct futhark_f32_3d **out1, struct futhark_f16_3d **out2, float *out3, float *out4, float *out5, const struct futhark_f16_3d *in0, const struct futhark_f16_3d *in1, const struct futhark_f16_3d *in2, const struct futhark_i64_1d *in3, const struct futhark_f16_3d *in4, const struct futhark_f16_3d *in5, const bool in6, const float in7, const float in8, const float in9, const float in10, const float in11, const float in12);
int futhark_entry_rsf_stack_forward(struct futhark_context *ctx, struct futhark_f16_3d **out0, const struct futhark_f16_3d *in0, const struct futhark_f16_3d *in1, const struct futhark_f16_3d *in2, const uint16_t in3, const uint16_t in4);
int futhark_entry_rsf_stack_inverse(struct futhark_context *ctx, struct futhark_f16_3d **out0, const struct futhark_f16_3d *in0, const struct futhark_f16_3d *in1, const struct futhark_f16_3d *in2, const uint16_t in3, const uint16_t in4);
int futhark_entry_scale_matrix_f32(struct futhark_context *ctx, struct futhark_f32_2d **out0, const struct futhark_f32_2d *in0, const float in1);
int futhark_entry_stack_spectral_normalize(struct futhark_context *ctx, struct futhark_f32_3d **out0, float *out1, float *out2, const struct futhark_f32_3d *in0, const float in1, const int64_t in2);
int futhark_entry_stack_update_sfd_master(struct futhark_context *ctx, struct futhark_f32_3d **out0, struct futhark_f32_3d **out1, struct futhark_f32_3d **out2, const struct futhark_f32_3d *in0, const struct futhark_f32_3d *in1, const struct futhark_f32_3d *in2, const struct futhark_f32_3d *in3, const float in4, const float in5, const float in6, const int64_t in7, const float in8, const float in9, const float in10);

// Miscellaneous
int futhark_context_sync(struct futhark_context *ctx);
void futhark_context_config_set_cache_file(struct futhark_context_config *cfg, const char *f);
char *futhark_context_get_error(struct futhark_context *ctx);
void futhark_context_set_logging_file(struct futhark_context *ctx, FILE *f);
void futhark_context_pause_profiling(struct futhark_context *ctx);
void futhark_context_unpause_profiling(struct futhark_context *ctx);
char *futhark_context_report(struct futhark_context *ctx);
int futhark_context_clear_caches(struct futhark_context *ctx);
#define FUTHARK_BACKEND_cuda
#define FUTHARK_SUCCESS 0
#define FUTHARK_PROGRAM_ERROR 2
#define FUTHARK_OUT_OF_MEMORY 3

#ifdef __cplusplus
}
#endif
